services:
  - type: web
    name: kenniskist-server
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node build/index.js
    healthCheckPath: /hi
    envVars:
      - key: NODE_ENV
        value: production
